packages:
  # specify a package in a direct subdir of the root
  - 'app'
  # all packages in direct subdirs of packages/
  - 'proto'
  # all packages in subdirs of components/
  - 'client'
  - 'bzl-ts'
  - 'server'
  - 'electron'